name: pokemon_tcg_scanner
description: A demo Flutter app for scanning Pokémon TCG cards using the camera.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Placeholder dependencies for camera and ML scanning
  camera: ^0.10.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/demo/
