name: 'Lint'

on:
  pull_request_target:
    branches:
      - main
      - story/*
      - bug/*
      - hotfix/*
    types:
      - opened
      - edited
      - reopened

permissions:
  pull-requests: write

jobs:
  lint:
    name: Lint PR
    uses: Veevarts/VeevartMultiActions/.github/workflows/lint.yml@feat/add-lint-pr-TAMERS-17
    secrets: inherit