name: Semantic Release

on:
  push:
    branches:
      - stable
      - stage
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  semantic-release:
    name: Semantic Release
    uses: Veevarts/VeevartMultiActions/.github/workflows/semantic-release.yml@main
    with:
      dry-run: ${{ inputs.dry-run || false }}
    secrets: inherit