name: Semantic Release

on:
  push:
    branches:
      - main
      - stable
      - beta-*
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run"
        required: false
        default: false
        type: boolean

jobs:
  semantic-release:
    name: Semantic Release
    permissions:
      contents: write
    uses: Veevarts/VeevartMultiActions/.github/workflows/semantic-release.yml@repication-release-manaeger-TAMER-19
    with:
      dry-run: ${{ inputs.dry-run || false }}
    secrets: inherit
