# This is the workflow that will be copied to other repositories.
# It runs autonomously in the target repository.

name: Mark Stale Issues and PRs

on:
  push:
  schedule:
    - cron: '0 5 * * 1-5' # Every day at 5 AM, Monday to Friday
  workflow_dispatch:

jobs:
  stale:
    runs-on: codebuild-GitHub_Action_${{ github.event.repository.name }}-${{ github.run_id }}-${{ github.run_attempt }}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Run actions/stale
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Stale configuration passed directly as inputs
          days-before-stale: 1
          days-before-close: 1
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          stale-issue-message: >
            This issue is stale because it has been inactive for 4 days.
            It will be closed in 3 days if no activity occurs.
          stale-pr-message: >
            This PR is stale because it has been inactive for 4 days.
            It will be closed in 3 days if no activity occurs.
          close-issue-message: >
            This issue was closed because it remained stale.
          close-pr-message: >
            This PR was closed because it remained stale.
          exempt-issue-labels: 'do-not-close,epic,blocked'
          exempt-pr-labels: 'do-not-close,epic,blocked'
          operations-per-run: 30
